import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#006d37',
        'primary-container': '#27ae60',
        'primary-fixed': '#7efba4',
        'primary-fixed-dim': '#61de8a',
        'on-primary': '#ffffff',
        'on-primary-container': '#00391a',
        'on-primary-fixed': '#00210c',
        'on-primary-fixed-variant': '#005228',
        'secondary': '#586062',
        'secondary-container': '#dae1e3',
        'secondary-fixed': '#dde4e6',
        'secondary-fixed-dim': '#c1c8ca',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5d6466',
        'on-secondary-fixed': '#161d1f',
        'on-secondary-fixed-variant': '#41484a',
        'tertiary': '#a7344c',
        'tertiary-container': '#f26d83',
        'tertiary-fixed': '#ffd9dc',
        'tertiary-fixed-dim': '#ffb2bb',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#670021',
        'on-tertiary-fixed': '#400011',
        'on-tertiary-fixed-variant': '#871b35',
        'surface': '#f4fbf1',
        'surface-dim': '#d5dcd2',
        'surface-bright': '#f4fbf1',
        'surface-variant': '#dde5db',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff6ec',
        'surface-container': '#e9f0e6',
        'surface-container-high': '#e3eae0',
        'surface-container-highest': '#dde5db',
        'surface-tint': '#006d37',
        'on-surface': '#171d17',
        'on-surface-variant': '#3d4a3f',
        'inverse-surface': '#2b322c',
        'inverse-on-surface': '#ecf3e9',
        'inverse-primary': '#61de8a',
        'outline': '#6d7a6e',
        'outline-variant': '#bccabc',
        'background': '#f4fbf1',
        'on-background': '#171d17',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'neutral-gray-50': '#F8F9FA',
        'neutral-gray-100': '#F1F2F6',
        'neutral-gray-600': '#747D8C',
        'neutral-gray-900': '#2F3542',
        'pet-green-vibrant': '#2ECC71',
        'pet-green-dark': '#1E8449',
        'error-red': '#E74C3C',
        'warning-yellow': '#F1C40F',
        'success-blue': '#3498DB',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        base: '4px',
        'container-margin': '20px',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'button-text': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'button-text': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
