CREATE TABLE notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    reservation_id    BIGINT       NULL,
    vaccination_id    BIGINT       NULL,
    notification_type VARCHAR(50)  NOT NULL,
    title             VARCHAR(100) NOT NULL,
    message           TEXT         NOT NULL,
    is_read           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at           TIMESTAMP    NULL,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
            REFERENCES users (id),
    CONSTRAINT fk_notifications_reservation
        FOREIGN KEY (reservation_id)
            REFERENCES reservations (id)
);

-- vaccination_id は 06_ERD §15 どおり列だけ作成する。
-- vaccinations テーブルが未作成のためFK制約は付けられない（Vaccination ドメイン実装時に追加する）

CREATE INDEX idx_notifications_user_id ON notifications (user_id);
CREATE INDEX idx_notifications_is_read ON notifications (is_read);
