CREATE TABLE pets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(50)  NOT NULL,
    pet_type    VARCHAR(30)  NOT NULL,
    birth_date  DATE         NULL,
    gender      VARCHAR(10)  NOT NULL,
    weight      DECIMAL(5,2) NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP    NULL,

    CONSTRAINT fk_pets_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
);

CREATE INDEX idx_pets_user_id ON pets (user_id);
