CREATE TABLE hospital_schedules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id     BIGINT      NOT NULL,
    available_date  DATE        NOT NULL,
    start_time      TIME        NOT NULL,
    end_time        TIME        NOT NULL,
    status          VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_hospital_schedules_hospital
        FOREIGN KEY (hospital_id)
            REFERENCES hospitals (id)
);

CREATE INDEX idx_hospital_schedules_hospital_id_available_date ON hospital_schedules (hospital_id, available_date);
