CREATE TABLE reservations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT       NOT NULL,
    pet_id                BIGINT       NOT NULL,
    hospital_id           BIGINT       NOT NULL,
    schedule_id           BIGINT       NOT NULL,
    reservation_datetime  TIMESTAMP    NOT NULL,
    status                VARCHAR(30)  NOT NULL DEFAULT 'REQUESTED',
    memo                  TEXT         NULL,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at            TIMESTAMP    NULL,

    CONSTRAINT fk_reservations_user
        FOREIGN KEY (user_id)
            REFERENCES users (id),
    CONSTRAINT fk_reservations_pet
        FOREIGN KEY (pet_id)
            REFERENCES pets (id),
    CONSTRAINT fk_reservations_hospital
        FOREIGN KEY (hospital_id)
            REFERENCES hospitals (id),
    CONSTRAINT fk_reservations_schedule
        FOREIGN KEY (schedule_id)
            REFERENCES hospital_schedules (id)
);

CREATE INDEX idx_reservations_user_id ON reservations (user_id);
CREATE INDEX idx_reservations_hospital_id ON reservations (hospital_id);
CREATE INDEX idx_reservations_schedule_id ON reservations (schedule_id);
