CREATE TABLE health_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id        BIGINT       NOT NULL,
    weight        DECIMAL(5,2) NULL,
    symptom       VARCHAR(255) NULL,
    memo          TEXT         NULL,
    recorded_date DATE         NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP    NULL,

    CONSTRAINT fk_health_records_pet
        FOREIGN KEY (pet_id)
            REFERENCES pets (id)
);

CREATE INDEX idx_health_records_pet_id ON health_records (pet_id);
