spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/daipetto?currentSchema=public
    username: daipetto_user
    password: local-dev-only-password

  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug